server:
  port: 8079

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: tjy941013
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  thymeleaf:
    view:
      suffix: .html
      prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.insence.pay.pojo

#级别 debug>info
logging:
  level:
    root: info
    com.insence.pay.dao: debug
    com.insence.pay.controller: debug
    com.insence.pay.service: debug


wx:
  notifyUrl: http://fyis9bv.nat.ipyingshe.com/pay/notify
  returnUrl: http://127.0.0.1
alipay:
  notifyUrl: http://fyis9bv.nat.ipyingshe.com/pay/notify
  returnUrl: http://127.0.0.1
